name: Simple Commands

on:
  push:
    branches:
      - main

jobs:
  execute_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Display current directory
      run: pwd # Prints the current working directory

    - name: List files in the directory
      run: ls -l  # Lists files in the current directory

    - name: Display system information
      run: uname -a  # Prints system information
