name: Simple Commands

on:
  push:
    branches:
      - main

jobs:
  execute_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Display current directory
      run: pwd 

    - name: List files in the directory
      run: ls -l  

    - name: Display system information
      run: uname -a  
