name: Simple Commands

on:
  push:
    branches:
      - main

jobs:
  execute_commands:
    runs-on: ubuntu-latest

    steps:
    - name: checkout directory
      uses: actions/checkout@v4
    - name: Display current directory
      run: cat README.md
